FROM node:18-alpine AS builder
WORKDIR /app
COPY ./package.json package.json
COPY ./package-lock.json package-lock.json
RUN npm ci

FROM gcr.io/distroless/nodejs18-debian11:nonroot
WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY . .

CMD [ "app.js" ]