FROM docker.io/library/node:22-slim AS builder

WORKDIR /app

COPY ./package.json package.json
COPY ./package-lock.json ./package-lock.json

RUN npm ci

COPY ./src/ src/
COPY ./public/ public/

RUN npm run build

FROM docker.io/library/node:22-slim AS deps
WORKDIR /app
COPY --from=builder /app/package.json package.json
COPY --from=builder /app/package-lock.json package-lock.json
COPY . .

RUN npm ci --omit=dev

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]